version: "3.5"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    network_mode: host
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=localhost:8500
    network_mode: host
    ports:
    - 9998:9998
    - 9999:9999

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    network_mode: host
    # volumes:
    #   - grafana:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    network_mode: host

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - mongo:/data/db

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    network_mode: host
    # volumes:
    #   - prometheus:/prometheus

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    network_mode: host
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    network_mode: host
    volumes: 
      - redis:/data

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    network_mode: host
    # volumes: 
    #   - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    ports:
      - 8200:8200
    network_mode: host
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  mongo:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local