global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'deliveries'
    static_configs:
      - targets: ['docker.for.win.localhost:5001']

  - job_name: 'orders'
    static_configs:
      - targets: ['docker.for.win.localhost:5002']

  - job_name: 'pricing'
    static_configs:
      - targets: ['docker.for.win.localhost:5003']


      

  
